# Generated by Django 5.0.1 on 2025-05-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.CharField(default='No comment', max_length=20),
            preserve_default=False,
        ),
    ]
