"""
Django settings for shoppit project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

from datetime import timedelta

from decouple import config

# --------------deploy-------------

import os
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent







# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c#p(gg_%*6y(-7x-(-q^d&-&c)3u_af6qyx_im72!e$@vja&2q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Configuration de base
ALLOWED_HOSTS = [
    "blaatoyao.onrender.com",  # Votre domaine principal
    "localhost",
    "127.0.0.1",
    ".onrender.com",  # Autorise tous les sous-domaines Render
]






# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'shop_app',
    'rest_framework',
]
# pip install django-cors-headers
CORS_ALLOWED_ORIGINS = [
    # "https://blaato.onrender.com",
    "https://bafa.onrender.com",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:8001"
] 
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True









MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shoppit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shoppit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# pour les images photos
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'core.CustomUser'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )

}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
}

# payment

FLUTTERWAVE_SECRET_KEY = "FLWSECK_TEST-c2b389002102e675794116e4dde185bd-X"


# -----------------------------------
PAYPAL_CLIENT_ID = 'AZvhTGGCzMJ9q_k6QYcfeGPpPsm3fGjy0FBO_8W3wyPvJG9IP73QGQ50_Rwv5F3Dc-rpQ06DqCzmVrcl'
PAYPAL_CLIENT_SECRET = 'ELh3HT5SdkLxTKymqEhzDLgweQQn_Cr4SXNwur5IirMcF8iA4EqJNuOQykMTBkA8sT_agbDlopkoecdm'
PAYPAL_MODE = 'sandbox'  # 'live' en production





REACT_BASE_URL =os.getenv("REACT_BASE_URL", "http://localhost:5173/")
PAYDUNYA_MODE = "test"
PAYDUNYA_CALLBACK_URL = f"{REACT_BASE_URL}/payment-status/"
# PAYDUNYA_MASTER_KEY = "4gZ4CvRz-eBuF-Wa8I-CRCy-xu9Yzf2Y5FFA"
# PAYDUNYA_PRIVATE_KEY = "test_private_85htEdDMFc4dG2Zp6EWRiOlI95L"
# PAYDUNYA_PUBLIC_KEY = "test_public_Hzj024u675ZlO0ZFmXluty6CHOg"
# PAYDUNYA_TOKEN = "cOcqaQ9HWIK6DhY1e5p2"


# PayDunya settings
PAYDUNYA_MODE = "live"  # ou "live" en production
PAYDUNYA_MASTER_KEY = "4gZ4CvRz-eBuF-Wa8I-CRCy-xu9Yzf2Y5FFA"
PAYDUNYA_PRIVATE_KEY = "live_private_xlZrb0GbmwCZTaCe8DolfNs3g7T"
PAYDUNYA_TOKEN = "TPzZK8uopIKARKspE0qp"
YOUR_BACKEND_DOMAIN ="http://localhost:5173/payment-status"


import os

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Par exemple, pour Gmail
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'charlesyao1602@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')  # Doit être défini dans .env
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

FRONTEND_URL = 'https://bafa.onrender.com'
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')